[package]
name = "guvm-rs"
version = "0.1.0"
authors = ["Aljoscha Meyer <mail@aljoscha-meyer.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gc = "0.3.3"
gc_derive = "0.3.2"
smol = "1.2.5"
